[credentials]

  [credentials.usernames.charitos]
  name = "Charitos"
  email = "charitos@thefashionproject.gr"
  password = "$2b$12$FIMklOsOkCAlLTFkaocG6eq2YN8peYSxnY4gY7abXzHsa2ou6IcMO"

  [credentials.usernames.panagiotis]
  name = "Panagiotis"
  email = "panagiotis@thefashionproject.gr"
  password = "$2b$12$Fx0HB79PmLfSl0W7SmoJGOIh4bb2Df.sq3j9Zdntysirh4MlFMJcS"

  [credentials.usernames.efi]
  name = "Efi"
  email = "efi.m@thefashionproject.gr"
  password = "$2b$12$Ox7w5g5DzmyJKTwL1MC0/e90sOeFmdOezhqsHiTdlZMFdBmEVXf8e"

[cookie]
name = "order-validator-auth"
key = "a1f5e61b-3c20-4a2b-8e5d-74a3c274a86e"  # ?????? ???????
expiry_days = 30
