[credentials]

  [credentials.usernames.charitos]
  name = "Charitos"
  email = "charitos@thefashionproject.gr"
  password = "$2b$12$FIMk1sOkCALLtFkaocG6eq2YN8peYSxnY4gY7abXzHsa2ou6IcMO"

  [credentials.usernames.panagiotis]
  name = "Panagiotis"
  email = "panagiotis@thefashionproject.gr"
  password = "$2b$12$Fx0HB79PmLfS10W7SmoJGOIH4bb2Df.sq3j9Zdntysirh4M1FMJcS"

  [credentials.usernames.efi]
  name = "Efi"
  email = "efi.m@thefashionproject.gr"
  password = "$2b$12$0x7w5g5DzmyJKTwL1MC0/e90s0eFmd0ezhqsHiTdIZMFdBmEVxF8e"

[cookie]
name = "order-validator-auth"
key = "a1f5e61b-3c20-4a2b-8e5d-74a3c274a86e"
expiry_days = 30
